FROM ambientum/php:7.3

WORKDIR /var/www/app
ADD . /var/www/app

USER root

ENV LIBRDKAFKA_VERSION v0.11.0
ENV BUILD_DEPS \
  autoconf \
        bash \
        build-base \
        git \
        pcre2-dev \
        python \
        php-pear \
        php-dev

RUN apk --no-cache --virtual .build-deps add ${BUILD_DEPS} \
    && cd /tmp \
    && git clone \
        --branch ${LIBRDKAFKA_VERSION} \
        --depth 1 \
        https://github.com/edenhill/librdkafka.git \
    && cd librdkafka \
    && ./configure \
    && make \
    && make install \
    && pecl install rdkafka \
    && echo "extension=rdkafka.so" >> /etc/php7/php.ini \
    && rm -rf /tmp/librdkafka \
    && apk del .build-deps \
